In [13]:
import sys
# install httpimport if not in current python environment
!{sys.executable} -m pip install httpimport

# import httpimport - this allows you to import remote
# modules from urls, like github
import httpimport

httpimport.INSECURE = True

# Import heatunits script / module from github
with httpimport.remote_repo('https://github.com/UCANR-IGIS/caladapt-py/tree/master/CalAdaptLib'):
    import HeatUnits as hu

# Import pandas
import pandas as pd

Requirement already satisfied: httpimport in c:\users\stfei\appdata\local\esri\conda\envs\arcgispro-py3-brat\lib\site-packages (0.9.2)

In [14]:
# CSV from degree day challenge
csv = r'C:\Users\stfei\Desktop\espartoa-weather-2020.csv'

# Read CSV into pandas dataframe
data = pd.read_csv(csv)

# add column for yesterdays min temp
data["tmin_tom"] = data["tmin"].shift(-1)
data.tmin_tom.fillna(data.tmin, inplace=True)

# add column for tomorrows max temp
data["tmax_yest"] = data["tmax"].shift(1)
data.tmax_yest.fillna(data.tmax, inplace=True)

# print data
data

       station        date  tmin  tmax  tmin_tom  tmax_yest
0    Esparto.A  2020-01-01    38    55      36.0       55.0
1    Esparto.A  2020-01-02    36    67      33.0       55.0
2    Esparto.A  2020-01-03    33    59      37.0       67.0
3    Esparto.A  2020-01-04    37    59      38.0       59.0
4    Esparto.A  2020-01-05    38    63      36.0       59.0
..         ...         ...   ...   ...       ...        ...
361  Esparto.A  2020-12-27    36    54      38.0       61.0
362  Esparto.A  2020-12-28    38    54      38.0       54.0
363  Esparto.A  2020-12-29    38    54      38.0       54.0
364  Esparto.A  2020-12-30    38    54      38.0       54.0
365  Esparto.A  2020-12-31    38    55      38.0       54.0

[366 rows x 6 columns]

In [15]:
# 1 = Hor. or 2 = Int. or 3 = Vert. Cutoff

# Apply each of the Degree Day Calculations using the heatunits script/module
data["SiSineHor"] = data.apply(lambda x: hu.HeatU(50, 70, 1, 1, 1, x['tmin'], x['tmax']), axis=1)
data["SiSineInt"] = data.apply(lambda x: hu.HeatU(50, 70, 1, 2, 1, x['tmin'], x['tmax']), axis=1)
data["SiSineVert"] = data.apply(lambda x: hu.HeatU(50, 70, 1, 3, 1, x['tmin'], x['tmax']), axis=1)

data["DoSineHor"] = data.apply(lambda x: hu.HeatU(50, 70, 2, 1, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)
data["DoSineInt"] = data.apply(lambda x: hu.HeatU(50, 70, 2, 2, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)
data["DoSineVert"] = data.apply(lambda x: hu.HeatU(50, 70, 2, 3, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)

data["SiTriHor"] = data.apply(lambda x: hu.HeatU(50, 70, 3, 1, 1, x['tmin'], x['tmax']), axis=1)
data["SiTriInt"] = data.apply(lambda x: hu.HeatU(50, 70, 3, 2, 1, x['tmin'], x['tmax']), axis=1)
data["SiTriVert"] = data.apply(lambda x: hu.HeatU(50, 70, 3, 3, 1, x['tmin'], x['tmax']), axis=1)

data["DoTriHor"] = data.apply(lambda x: hu.HeatU(50, 70, 4, 1, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)
data["DoTriInt"] = data.apply(lambda x: hu.HeatU(50, 70, 4, 2, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)
data["DoTriVert"] = data.apply(lambda x: hu.HeatU(50, 70, 4, 3, 1, x['tmin'], x['tmax'], x['tmin_tom'], x['tmax_yest']), axis=1)

data = data.round({'SiSineHor': 2, 'SiSineInt': 2, 'SiSineVert': 2,
                   'DoSineHor': 2, 'DoSineInt': 2, 'DoSineVert': 2,
                   'SiTriHor': 2, 'SiTriInt': 2, 'SiTriVert': 2,
                   'DoTriHor': 2, 'DoTriInt': 2, 'DoTriVert': 2})

# Print the resulting dataframe with each calculation as a column
data

,station,date,tmin,tmax,tmin_tom,tmax_yest,SiSineHor,SiSineInt,SiSineVert,DoSineHor,DoSineInt,DoSineVert,SiTriHor,SiTriInt,SiTriVert,DoTriHor,DoTriInt,DoTriVert
0,Esparto.A,2020-01-01,38,55,36.0,55.0,1.19,1.19,1.19,1.15,1.15,1.15,0.74,0.74,0.74,0.70,0.70,0.70
1,Esparto.A,2020-01-02,36,67,33.0,55.0,5.71,5.71,5.71,5.56,5.56,5.56,4.66,4.66,4.66,4.46,4.46,4.46
2,Esparto.A,2020-01-03,33,59,37.0,67.0,2.34,2.34,2.34,2.45,2.45,2.45,1.56,1.56,1.56,1.70,1.70,1.70
3,Esparto.A,2020-01-04,37,59,38.0,59.0,2.56,2.56,2.56,2.59,2.59,2.59,1.84,1.84,1.84,1.88,1.88,1.88
4,Esparto.A,2020-01-05,38,63,36.0,59.0,4.23,4.23,4.23,4.14,4.14,4.14,3.38,3.38,3.38,3.25,3.25,3.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,Esparto.A,2020-12-27,36,54,38.0,61.0,0.82,0.82,0.82,0.85,0.85,0.85,0.44,0.44,0.44,0.47,0.47,0.47
362,Esparto.A,2020-12-28,38,54,38.0,54.0,0.87,0.87,0.87,0.87,0.87,0.87,0.50,0.50,0.50,0.50,0.50,0.50
363,Esparto.A,2020-12-29,38,54,38.0,54.0,0.87,0.87,0.87,0.87,0.87,0.87,0.50,0.50,0.50,0.50,0.50,0.50
364,Esparto.A,2020-12-30,38,54,38.0,54.0,0.87,0.87,0.87,0.87,0.87,0.87,0.50,0.50,0.50,0.50,0.50,0.50
365,Esparto.A,2020-12-31,38,55,38.0,54.0,1.19,1.19,1.19,1.19,1.19,1.19,0.74,0.74,0.74,0.74,0.74,0.74

In [16]:
# Example of using help to query function for parameters
help(hu.HeatU)

Help on function HeatU in module HeatUnits:

HeatU(lthres, cthres, cm, coff, ci, tmin, tmax, tmin_tomm=0, tmax_yest=0)

In [12]:
# example of subsetting rows.  In this case by date
above_35 = data[data["date"] == '2020-03-31']
above_35

,station,date,tmin,tmax,tmin_tom,tmax_yest,SiSineHor,SiSineInt,SiSineVert,DoSineHor,DoSineInt,DoSineVert,SiTriHor,SiTriInt,SiTriVert,DoTriHor,DoTriInt,DoTriVert
90,Esparto.A,2020-03-31,52,72,46.0,67.0,11.73,11.46,7.63,10.58,10.33,6.75,11.9,11.8,9.9,10.57,10.48,8.8